# This spec file is terrible.
# Nobody should ever use this.
# This was Major's fumbling in the dark.
# 😜

# Generated by go2rpm 1.9.0
%bcond_without check

# https://github.com/redhatcloudx/ocb-test
%global goipath         github.com/redhatcloudx/ocb-test
%global commit          5d53a1920978acf43d46e96c23c914588eeac922

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -f


%global common_description %{expand:
# FIXME}

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        None

License:        # FIXME
URL:            %{gourl}
Source0:        %{gosource}
Source1:        https://github.com/open-telemetry/opentelemetry-collector/archive/refs/tags/v0.93.0.tar.gz
Source2:        https://github.com/open-telemetry/opentelemetry-collector-contrib/archive/c06bed3f5befcb4cc9d2bd53610545d7fa269475/opentelemetry-collector-contrib-c06bed3f5befcb4cc9d2bd53610545d7fa269475.tar.gz


BuildRequires: golang(github.com/alecthomas/participle/v2)
BuildRequires: golang(github.com/alecthomas/participle/v2/lexer)
BuildRequires: golang(github.com/apache/thrift/lib/go/thrift)
BuildRequires: golang(github.com/aws/aws-sdk-go/aws/credentials)
BuildRequires: golang(github.com/aws/aws-sdk-go/aws/signer/v4)
BuildRequires: golang(github.com/bmatcuk/doublestar/v4)
BuildRequires: golang(github.com/cenkalti/backoff/v4)
BuildRequires: golang(github.com/census-instrumentation/opencensus-proto/gen-go/agent/common/v1)
BuildRequires: golang(github.com/census-instrumentation/opencensus-proto/gen-go/agent/metrics/v1)
BuildRequires: golang(github.com/census-instrumentation/opencensus-proto/gen-go/agent/trace/v1)
BuildRequires: golang(github.com/census-instrumentation/opencensus-proto/gen-go/metrics/v1)
BuildRequires: golang(github.com/census-instrumentation/opencensus-proto/gen-go/resource/v1)
BuildRequires: golang(github.com/census-instrumentation/opencensus-proto/gen-go/trace/v1)
BuildRequires: golang(github.com/cespare/xxhash/v2)
BuildRequires: golang(github.com/expr-lang/expr)
BuildRequires: golang(github.com/expr-lang/expr/ast)
BuildRequires: golang(github.com/expr-lang/expr/vm)
BuildRequires: golang(github.com/fsnotify/fsnotify)
BuildRequires: golang(github.com/gobwas/glob)
BuildRequires: golang(github.com/gogo/protobuf/gogoproto)
BuildRequires: golang(github.com/gogo/protobuf/jsonpb)
BuildRequires: golang(github.com/gogo/protobuf/proto)
BuildRequires: golang(github.com/go-kit/log)
BuildRequires: golang(github.com/go-kit/log/level)
BuildRequires: golang(github.com/golang/protobuf/ptypes/wrappers)
BuildRequires: golang(github.com/golang/snappy)
BuildRequires: golang(github.com/google/uuid)
BuildRequires: golang(github.com/gorilla/mux)
BuildRequires: golang(github.com/grpc-ecosystem/grpc-gateway/v2/runtime)
BuildRequires: golang(github.com/hashicorp/golang-lru/simplelru)
BuildRequires: golang(github.com/hashicorp/golang-lru/v2)
BuildRequires: golang(github.com/hashicorp/go-version)
BuildRequires: golang(github.com/iancoleman/strcase)
BuildRequires: golang(github.com/IBM/sarama)
BuildRequires: golang(github.com/influxdata/go-syslog/v3)
BuildRequires: golang(github.com/influxdata/go-syslog/v3/nontransparent)
BuildRequires: golang(github.com/influxdata/go-syslog/v3/octetcounting)
BuildRequires: golang(github.com/influxdata/go-syslog/v3/rfc3164)
BuildRequires: golang(github.com/influxdata/go-syslog/v3/rfc5424)
BuildRequires: golang(github.com/jaegertracing/jaeger/cmd/agent/app/configmanager)
BuildRequires: golang(github.com/jaegertracing/jaeger/cmd/agent/app/configmanager/grpc)
BuildRequires: golang(github.com/jaegertracing/jaeger/cmd/agent/app/httpserver)
BuildRequires: golang(github.com/jaegertracing/jaeger/cmd/agent/app/processors)
BuildRequires: golang(github.com/jaegertracing/jaeger/cmd/agent/app/servers)
BuildRequires: golang(github.com/jaegertracing/jaeger/cmd/agent/app/servers/thriftudp)
BuildRequires: golang(github.com/jaegertracing/jaeger/cmd/collector/app/sampling)
BuildRequires: golang(github.com/jaegertracing/jaeger/cmd/collector/app/sampling/strategystore)
BuildRequires: golang(github.com/jaegertracing/jaeger/model)
BuildRequires: golang(github.com/jaegertracing/jaeger/model/converter/thrift/zipkin)
BuildRequires: golang(github.com/jaegertracing/jaeger/pkg/metrics)
BuildRequires: golang(github.com/jaegertracing/jaeger/plugin/sampling/strategystore/static)
BuildRequires: golang(github.com/jaegertracing/jaeger/proto-gen/api_v2)
BuildRequires: golang(github.com/jaegertracing/jaeger/thrift-gen/agent)
BuildRequires: golang(github.com/jaegertracing/jaeger/thrift-gen/baggage)
BuildRequires: golang(github.com/jaegertracing/jaeger/thrift-gen/jaeger)
BuildRequires: golang(github.com/jaegertracing/jaeger/thrift-gen/zipkincore)
BuildRequires: golang(github.com/json-iterator/go)
BuildRequires: golang(github.com/klauspost/compress/zstd)
BuildRequires: golang(github.com/knadh/koanf/maps)
BuildRequires: golang(github.com/knadh/koanf/providers/confmap)
BuildRequires: golang(github.com/knadh/koanf/v2)
BuildRequires: golang(github.com/lightstep/go-expohisto/structure)
BuildRequires: golang(github.com/mitchellh/hashstructure/v2)
BuildRequires: golang(github.com/mitchellh/mapstructure)
BuildRequires: golang(github.com/mostynb/go-grpc-compression/nonclobbering/snappy)
BuildRequires: golang(github.com/mostynb/go-grpc-compression/nonclobbering/zstd)
BuildRequires: golang(github.com/openzipkin/zipkin-go/model)
BuildRequires: golang(github.com/openzipkin/zipkin-go/proto/zipkin_proto3)
BuildRequires: golang(github.com/openzipkin/zipkin-go/reporter)
BuildRequires: golang(github.com/prometheus/client_golang/prometheus)
BuildRequires: golang(github.com/prometheus/client_golang/prometheus/promhttp)
BuildRequires: golang(github.com/prometheus/common/config)
BuildRequires: golang(github.com/prometheus/common/model)
BuildRequires: golang(github.com/prometheus/prometheus/config)
BuildRequires: golang(github.com/prometheus/prometheus/discovery)
BuildRequires: golang(github.com/prometheus/prometheus/discovery/http)
BuildRequires: golang(github.com/prometheus/prometheus/discovery/install)
BuildRequires: golang(github.com/prometheus/prometheus/discovery/kubernetes)
BuildRequires: golang(github.com/prometheus/prometheus/model/exemplar)
BuildRequires: golang(github.com/prometheus/prometheus/model/histogram)
BuildRequires: golang(github.com/prometheus/prometheus/model/labels)
BuildRequires: golang(github.com/prometheus/prometheus/model/metadata)
BuildRequires: golang(github.com/prometheus/prometheus/model/textparse)
BuildRequires: golang(github.com/prometheus/prometheus/model/value)
BuildRequires: golang(github.com/prometheus/prometheus/scrape)
BuildRequires: golang(github.com/prometheus/prometheus/storage)
BuildRequires: golang(github.com/relvacode/iso8601)
BuildRequires: golang(github.com/rs/cors)
BuildRequires: golang(github.com/shirou/gopsutil/v3/common)
BuildRequires: golang(github.com/shirou/gopsutil/v3/mem)
BuildRequires: golang(github.com/shirou/gopsutil/v3/process)
BuildRequires: golang(github.com/soheilhy/cmux)
BuildRequires: golang(github.com/spf13/cobra)
BuildRequires: golang(github.com/tilinna/clock)
BuildRequires: golang(github.com/valyala/fastjson)
BuildRequires: golang(github.com/xdg-go/scram)
BuildRequires: golang(golang.org/x/exp/constraints)
BuildRequires: golang(golang.org/x/exp/slices)
BuildRequires: golang(golang.org/x/net/http2)
BuildRequires: golang(golang.org/x/oauth2)
BuildRequires: golang(golang.org/x/oauth2/clientcredentials)
BuildRequires: golang(golang.org/x/text/encoding)
BuildRequires: golang(golang.org/x/text/encoding/ianaindex)
BuildRequires: golang(golang.org/x/text/encoding/unicode)
BuildRequires: golang(golang.org/x/text/transform)
BuildRequires: golang(gonum.org/v1/gonum/graph)
BuildRequires: golang(gonum.org/v1/gonum/graph/encoding/dot)
BuildRequires: golang(gonum.org/v1/gonum/graph/simple)
BuildRequires: golang(gonum.org/v1/gonum/graph/topo)
BuildRequires: golang(google.golang.org/genproto/googleapis/rpc/errdetails)
BuildRequires: golang(google.golang.org/genproto/googleapis/rpc/status)
BuildRequires: golang(google.golang.org/grpc)
BuildRequires: golang(google.golang.org/grpc/balancer)
BuildRequires: golang(google.golang.org/grpc/codes)
BuildRequires: golang(google.golang.org/grpc/credentials)
BuildRequires: golang(google.golang.org/grpc/credentials/insecure)
BuildRequires: golang(google.golang.org/grpc/credentials/oauth)
BuildRequires: golang(google.golang.org/grpc/encoding/gzip)
BuildRequires: golang(google.golang.org/grpc/grpclog)
BuildRequires: golang(google.golang.org/grpc/health)
BuildRequires: golang(google.golang.org/grpc/health/grpc_health_v1)
BuildRequires: golang(google.golang.org/grpc/keepalive)
BuildRequires: golang(google.golang.org/grpc/metadata)
BuildRequires: golang(google.golang.org/grpc/peer)
BuildRequires: golang(google.golang.org/grpc/reflection)
BuildRequires: golang(google.golang.org/grpc/status)
BuildRequires: golang(google.golang.org/protobuf/proto)
BuildRequires: golang(google.golang.org/protobuf/types/known/timestamppb)
BuildRequires: golang(google.golang.org/protobuf/types/known/wrapperspb)
BuildRequires: golang(go.opencensus.io/metric)
BuildRequires: golang(go.opencensus.io/metric/metricdata)
BuildRequires: golang(go.opencensus.io/metric/metricproducer)
BuildRequires: golang(go.opencensus.io/resource/resourcekeys)
BuildRequires: golang(go.opencensus.io/stats)
BuildRequires: golang(go.opencensus.io/stats/view)
BuildRequires: golang(go.opencensus.io/tag)
BuildRequires: golang(go.opencensus.io/trace)
BuildRequires: golang(go.opentelemetry.io/contrib/config)
BuildRequires: golang(go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc)
BuildRequires: golang(go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp)
BuildRequires: golang(go.opentelemetry.io/contrib/propagators/b3)
BuildRequires: golang(go.opentelemetry.io/contrib/zpages)
BuildRequires: golang(go.opentelemetry.io/otel)
BuildRequires: golang(go.opentelemetry.io/otel/attribute)
BuildRequires: golang(go.opentelemetry.io/otel/bridge/opencensus)
BuildRequires: golang(go.opentelemetry.io/otel/codes)
BuildRequires: golang(go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc)
BuildRequires: golang(go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp)
BuildRequires: golang(go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc)
BuildRequires: golang(go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp)
BuildRequires: golang(go.opentelemetry.io/otel/exporters/prometheus)
BuildRequires: golang(go.opentelemetry.io/otel/exporters/stdout/stdoutmetric)
BuildRequires: golang(go.opentelemetry.io/otel/exporters/stdout/stdouttrace)
BuildRequires: golang(go.opentelemetry.io/otel/metric)
BuildRequires: golang(go.opentelemetry.io/otel/metric/noop)
BuildRequires: golang(go.opentelemetry.io/otel/propagation)
BuildRequires: golang(go.opentelemetry.io/otel/sdk/instrumentation)
BuildRequires: golang(go.opentelemetry.io/otel/sdk/metric)
BuildRequires: golang(go.opentelemetry.io/otel/sdk/resource)
BuildRequires: golang(go.opentelemetry.io/otel/sdk/trace)
BuildRequires: golang(go.opentelemetry.io/otel/trace)
BuildRequires: golang(go.opentelemetry.io/otel/trace/noop)
BuildRequires: golang(gopkg.in/yaml.v2)
BuildRequires: golang(gopkg.in/yaml.v3)
BuildRequires: golang(go.uber.org/multierr)
BuildRequires: golang(go.uber.org/zap)
BuildRequires: golang(go.uber.org/zap/zapcore)
BuildRequires: golang(go.uber.org/zap/zapgrpc)

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

cd ../../../
mkdir -p go.opentelemetry.io/collector
tar -C go.opentelemetry.io/collector --strip-components=1 -xf %{SOURCE1}

mkdir -p github.com/open-telemetry/opentelemetry-collector-contrib
tar -C github.com/open-telemetry/opentelemetry-collector-contrib --strip-components=1 -xf %{SOURCE2}

cd github.com/redhatcloudx/ocb-test
ls -al


%build
%gobuild -o %{gobuilddir}/bin/ocb-test %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
